/*
 * This code was written as part of a senior project, for the
 * Computer Science department at California Polytechnic State
 * University, San Luis Obispo, in Winter/Spring 2018.
 * The author of the project is Bryan McGuffin: bmcguffi@calpoly.edu
 * Advisor is John Clements: aoeuclements@brinckerhoff.org
 */
package Views;

import Controls.I_Controller;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Bryan McGuffin
 */
public class ScriptOverview extends javax.swing.JFrame implements I_View
{

	private I_Controller ctrl;

	/**
	 * Creates new form ScriptOverview
	 */
	public ScriptOverview(I_Controller c)
	{
		initComponents();
		ctrl = c;
	}

	@Override
	public void update(Observable o, Object arg)
	{
		throw new UnsupportedOperationException("Not supported yet."); // To change body of generated methods, choose
																		// Tools | Templates.
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(110, 110), new java.awt.Dimension(110, 110),
				new java.awt.Dimension(110, 110));
		filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 40), new java.awt.Dimension(40, 40),
				new java.awt.Dimension(40, 40));
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		jMenuBar1 = new javax.swing.JMenuBar();
		MenuBtnFile = new javax.swing.JMenu();
		MenuBtnPlotlines = new javax.swing.JMenu();
		MenuBtnEvents = new javax.swing.JMenu();
		MenuBtnMedia = new javax.swing.JMenu();
		MenuBtnOptions = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 742, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 504, Short.MAX_VALUE));

		jScrollPane1.setViewportView(jPanel1);

		MenuBtnFile.setText("File");
		jMenuBar1.add(MenuBtnFile);

		MenuBtnPlotlines.setText("Plotlines");
		jMenuBar1.add(MenuBtnPlotlines);

		MenuBtnEvents.setText("Events");
		jMenuBar1.add(MenuBtnEvents);

		MenuBtnMedia.setText("Media");
		jMenuBar1.add(MenuBtnMedia);

		MenuBtnOptions.setText("Options");
		jMenuBar1.add(MenuBtnOptions);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700,
										Short.MAX_VALUE))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenu MenuBtnEvents;
	private javax.swing.JMenu MenuBtnFile;
	private javax.swing.JMenu MenuBtnMedia;
	private javax.swing.JMenu MenuBtnOptions;
	private javax.swing.JMenu MenuBtnPlotlines;
	private javax.swing.Box.Filler filler1;
	private javax.swing.Box.Filler filler2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
